/* token.h */

typedef enum {
        ID = 256, 
	NUM, 
        ARR,
        BOOL,
        CHAR,
        ELSE,
        FALSE,
        FOR,
        FUNCTION,
        IF,
        INT,
        PRINT,
        RETURN,
        STR,
        TRUE,
        VOID,
        WHILE,
        LEQ,
        GEQ,
        EQUAL,
        NEQ,
        AND,
        OR,
        NOT = 33,
        REST = 37,
        LPAREN = 40,
        RPAREN = 41,
        MUL = 42,
        PLUS = 43,
        COMMA = 44,
        MINUS = 45,
        DIV = 47,
        COLON = 58,
        SCOLON = 59,
        LESS = 60,
        EQS = 61,
        GREAT = 62,
        LBRACK = 91,
        RBRACK = 93,
        LBRACE = 123,
        RBRACE = 125,
        BSLASH,
	ERROR
} token_t; 

